### ISSUE TITLE
Multiple buttons in the same row

### ISSUE THREAD

**Issue by TheDusty01** [feelingnothing/DSharpPlus.Menus#4]
Hey, I am trying to use multiple buttons in the same row. I tried the following:
```cs
[StaticPrimaryButton(nameof(OnButtonClick1), "Button 1", row: ButtonPosition.First)]
public async Task OnButtonClick1(ButtonContext ctx)
{
    // Stuff
}

[StaticSecondaryButton(nameof(OnButtonClick2), "Button 2", row: ButtonPosition.First)]
public async Task OnButtonClick2(ButtonContext ctx)
{
    // Stuff
}
```
The problem is that this doesn't work. The 2 buttons aren't in the same row.

Is there any specific way to achieve this or is this simply not supported yet?

**Comment by feelingnothing** [comment]
I looked into how menus's buttons serialized to message components and could not find the issue, I'll debug it when I could, now on hold

**Comment by feelingnothing** [comment]
New version had been made that fixes that issue, closed
