### ISSUE TITLE
Ref type in ButtonAttribute

### ISSUE THREAD

**Issue by VelvetThePanda** [feelingnothing/DSharpPlus.Menus#7]
Attribute properties must be compile-time constants. Ref types are not compile-time constants. I suggest taking a string instead, and checking if it's an id with `ulong.Parse`

**Comment by feelingnothing** [comment]
Could really understand about what part of the button attribute you are talking about, especially about ref types, could you please elaborate more about your suggestion

**Comment by VelvetThePanda** [comment]
The emoji property. Because you have to instantiate it, it's not a compile-time constant

**Comment by feelingnothing** [comment]
ulong type would work, but is it possible to get standard emojies from it? Emoji component accept string too, did not get the `ulong.Parse` part

**Comment by VelvetThePanda** [comment]
Replace the emoji with a string, and if ulong.TryParse returns true you
construct a new emoji and pass the parsed ID, otherwise you just pass the
string

**Comment by feelingnothing** [comment]
I think it would be intuitive to have two constructors with string and ulong as emojies but it would require more lines then it should be, your solution seems very easy to implement, thanks for elaboration, when I read it I thought about constructor parameters type, thank you, almost implemented it

**Comment by feelingnothing** [comment]
Implemented in `1.0.3.5`
