### ISSUE TITLE
Buttons seem to be added in reversed order

### ISSUE THREAD

**Issue by VelvetThePanda** [feelingnothing/DSharpPlus.Menus#9]

**Comment by VelvetThePanda** [comment]
![](https://cdn.velvetthepanda.dev/Nw67s.png)

![](https://cdn.velvetthepanda.dev/Uf0Qn.png)

**Comment by VelvetThePanda** [comment]
Obviously, specifying order would fix this, but still

**Comment by VelvetThePanda** [comment]
Okay, after some very non-extensive testing, I've determined that buttons are in fact registered in descending order from which they're defined in code

![](https://cdn.velvetthepanda.dev/SAcSg.png)

**Comment by VelvetThePanda** [comment]
![](https://cdn.velvetthepanda.dev/T3kQK.png)

**Comment by feelingnothing** [comment]
Fixed
